{
"openapi": "3.0.1",
"info": {
"title": "OpenAPI definition",
"version": "v0"
},
"servers": [
{
"url": "http://localhost:8181",
"description": "Generated server url"
}
],
"paths": {
"/api/leave/{LeaveId}": {
"put": {
"tags": [
"leave-controller"
],
"operationId": "updateLeaveRequest",
"parameters": [
{
"name": "LeaveId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
}
}
}
},
"delete": {
"tags": [
"leave-controller"
],
"operationId": "deleteLeaveRequest",
"parameters": [
{
"name": "LeaveId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK"
}
}
}
},
"/api/dept/update/{deptId}": {
"put": {
"tags": [
"department-controller"
],
"operationId": "update",
"parameters": [
{
"name": "deptId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Department"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/user/login": {
"post": {
"tags": [
"user-controller"
],
"operationId": "login",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/LoginDTO"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/user/add": {
"post": {
"tags": [
"user-controller"
],
"operationId": "register",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/AddUserDto"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/leave/{LeaveId}/reject": {
"post": {
"tags": [
"leave-controller"
],
"operationId": "rejectLeaveRequest",
"parameters": [
{
"name": "LeaveId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
}
}
}
}
},
"/api/leave/{LeaveId}/approve": {
"post": {
"tags": [
"leave-controller"
],
"operationId": "approveLeaveRequest",
"parameters": [
{
"name": "LeaveId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
}
}
}
}
},
"/api/leave/create": {
"post": {
"tags": [
"leave-controller"
],
"operationId": "createLeaveRequest",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"$ref": "#/components/schemas/Leave"
}
}
}
}
}
}
},
"/api/dept/add": {
"post": {
"tags": [
"department-controller"
],
"operationId": "register_1",
"requestBody": {
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Department"
}
}
},
"required": true
},
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/user/{userId}": {
"get": {
"tags": [
"user-controller"
],
"operationId": "getUserById",
"parameters": [
{
"name": "userId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/user/verify/{token}": {
"get": {
"tags": [
"user-controller"
],
"operationId": "verifyEmail",
"parameters": [
{
"name": "token",
"in": "path",
"required": true,
"schema": {
"type": "string"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/leave/getAllLeaves": {
"get": {
"tags": [
"leave-controller"
],
"operationId": "getAllLeaveRequests",
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "array",
"items": {
"$ref": "#/components/schemas/Leave"
}
}
}
}
}
}
}
},
"/api/dept/getAllEmpByDept/{deptId}": {
"get": {
"tags": [
"department-controller"
],
"operationId": "getAllUsers",
"parameters": [
{
"name": "deptId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/dept/getAllDepartments": {
"get": {
"tags": [
"department-controller"
],
"operationId": "getAll",
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/dept/get/{deptId}": {
"get": {
"tags": [
"department-controller"
],
"operationId": "getById",
"parameters": [
{
"name": "deptId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
},
"/api/dept/delete/{deptId}": {
"delete": {
"tags": [
"department-controller"
],
"operationId": "delete",
"parameters": [
{
"name": "deptId",
"in": "path",
"required": true,
"schema": {
"type": "integer",
"format": "int64"
}
}
],
"responses": {
"200": {
"description": "OK",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
}
},
"components": {
"schemas": {
"Department": {
"required": [
"deptName"
],
"type": "object",
"properties": {
"deptId": {
"type": "integer",
"format": "int64"
},
"deptName": {
"type": "string"
}
}
},
"Leave": {
"required": [
"employee",
"endDate",
"reason",
"startDate",
"status"
],
"type": "object",
"properties": {
"leaveId": {
"type": "integer",
"format": "int64"
},
"employee": {
"$ref": "#/components/schemas/User"
},
"startDate": {
"type": "string",
"format": "date-time"
},
"endDate": {
"type": "string",
"format": "date-time"
},
"reason": {
"type": "string"
},
"status": {
"type": "string"
}
}
},
"User": {
"type": "object",
"properties": {
"userId": {
"type": "integer",
"format": "int32"
},
"email": {
"type": "string"
},
"username": {
"type": "string"
},
"firstName": {
"type": "string"
},
"middleName": {
"type": "string"
},
"lastName": {
"type": "string"
},
"gender": {
"type": "string"
},
"dept": {
"$ref": "#/components/schemas/Department"
},
"address": {
"type": "string"
},
"profilePhoto": {
"type": "string"
},
"role": {
"type": "string"
},
"emailVerified": {
"type": "boolean"
},
"birthDate": {
"type": "string",
"format": "date-time"
},
"joinDate": {
"type": "string",
"format": "date-time"
}
}
},
"LoginDTO": {
"required": [
"email",
"password"
],
"type": "object",
"properties": {
"email": {
"type": "string"
},
"password": {
"maxLength": 2147483647,
"minLength": 8,
"type": "string"
}
}
},
"AddUserDto": {
"required": [
"birthDate",
"deptId",
"email",
"firstName",
"gender",
"lastName",
"middleName",
"password",
"role",
"userName"
],
"type": "object",
"properties": {
"userName": {
"type": "string"
},
"email": {
"type": "string"
},
"password": {
"maxLength": 2147483647,
"minLength": 8,
"type": "string"
},
"firstName": {
"type": "string"
},
"middleName": {
"type": "string"
},
"lastName": {
"type": "string"
},
"gender": {
"type": "string"
},
"deptId": {
"type": "integer",
"format": "int64"
},
"role": {
"type": "string"
},
"birthDate": {
"type": "string",
"format": "date-time"
}
}
}
}
}
}